sudo: required
services:
  - docker

language: node_js

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

node_js:
  - "6"
  - "5"

script:
  - npm install
  - npm test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker build -t packebian/backend-controller:stable . ;
      docker push packebian/backend-controller:stable;
    fi
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
      docker build -t packebian/backend-controller:latest . ;
      docker push packebian/backend-controller:latest;
    fi

branches:
  only:
    - master
    - develop
