sudo: required
services:
  - docker

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - curl -L https://github.com/docker/compose/releases/download/1.11.1/run.sh > docker-compose
  - PATH=$(pwd):$PATH
  - chmod +x docker-compose && docker-compose --version
  - docker build -t packebian/backend-controller:latest .
  - docker tag packebian/backend-controller:latest packebian/backend-controller:stable
  - cd env
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
      git fetch origin ;
      git checkout develop ;
    fi
  - cd ..

script:
  - cd env
  - docker-compose up -d mongodb
  - docker-compose run sails npm test # Run tests

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker push packebian/backend-controller:stable ;
    fi
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
      docker push packebian/backend-controller:latest ;
    fi

branches:
  only:
    - master
    - develop
