FORMAT: 1A
HOST: BASE_URL

# Packebian API
[Markdown](http://daringfireball.net/projects/markdown/syntax) **formatted** description.

<!-- include(header.md) -->

# Data Structures
<!-- include(models/auth.md) -->
<!-- include(models/user.md) -->
<!-- include(models/ticket.md) -->
<!-- include(models/vote.md) -->
<!-- include(models/package.md) -->
<!-- include(models/build.md) -->
<!-- include(models/message.md) -->


# Group Login & Logout
<!-- include(controllers/auth/login.md) -->
<!-- include(controllers/auth/logout.md) -->


# Group User
<!-- include(controllers/user/getAll.md) -->
<!-- include(controllers/user/post.md) -->
<!-- include(controllers/user/get.md) -->
<!-- include(controllers/user/put.md) -->
<!-- include(controllers/user/delete.md) -->


# Group Ticket
<!-- include(controllers/ticket/getAll.md) -->
<!-- include(controllers/ticket/post.md) -->
<!-- include(controllers/ticket/get.md) -->
<!-- include(controllers/ticket/put.md) -->
<!-- include(controllers/ticket/delete.md) -->


# Group Vote
<!-- include(controllers/vote/getAll.md) -->
<!-- include(controllers/vote/post.md) -->
<!-- include(controllers/vote/get.md) -->
<!-- include(controllers/vote/put.md) -->
<!-- include(controllers/vote/delete.md) -->


# Group Package
<!-- include(controllers/package/getAll.md) -->
<!-- include(controllers/package/post.md) -->
<!-- include(controllers/package/get.md) -->
<!-- include(controllers/package/put.md) -->
<!-- include(controllers/package/delete.md) -->


# Group Build
<!-- include(controllers/build/getAll.md) -->
<!-- include(controllers/build/post.md) -->
<!-- include(controllers/build/get.md) -->
<!-- include(controllers/build/put.md) -->
<!-- include(controllers/build/delete.md) -->


# Group Message
<!-- include(controllers/message/getAll.md) -->
<!-- include(controllers/message/post.md) -->
<!-- include(controllers/message/get.md) -->
<!-- include(controllers/message/put.md) -->
<!-- include(controllers/message/delete.md) -->


<!-- include(footer.md) -->
