FORMAT: 1A
HOST: BASE_URL

# Packebian API

# Data Structures
<!-- include(models/user.md) -->
<!-- include(models/ticket.md) -->
<!-- include(models/vote.md) -->
<!-- include(models/package.md) -->
<!-- include(models/build.md) -->
<!-- include(models/message.md) -->

# Creation of ressources
<!-- include(controllers/user/post.md) -->
<!-- include(controllers/ticket/post.md) -->
<!-- include(controllers/vote/post.md) -->
<!-- include(controllers/package/post.md) -->
<!-- include(controllers/build/post.md) -->
<!-- include(controllers/message/post.md) -->


# Retrieve single ressources
<!-- include(controllers/user/get.md) -->
<!-- include(controllers/ticket/get.md) -->
<!-- include(controllers/vote/get.md) -->
<!-- include(controllers/package/get.md) -->
<!-- include(controllers/build/get.md) -->
<!-- include(controllers/message/get.md) -->

# Retrieve lists of ressources
<!-- include(controllers/user/getAll.md) -->
<!-- include(controllers/ticket/getAll.md) -->
<!-- include(controllers/vote/getAll.md) -->
<!-- include(controllers/package/getAll.md) -->
<!-- include(controllers/build/getAll.md) -->
<!-- include(controllers/message/getAll.md) -->

# Update ressources
<!-- include(controllers/user/put.md) -->
<!-- include(controllers/ticket/put.md) -->
<!-- include(controllers/vote/put.md) -->
<!-- include(controllers/package/put.md) -->
<!-- include(controllers/build/put.md) -->
<!-- include(controllers/message/put.md) -->


# Delete ressources
<!-- include(controllers/message/delete.md) -->
<!-- include(controllers/build/delete.md) -->
<!-- include(controllers/package/delete.md) -->
<!-- include(controllers/vote/delete.md) -->
<!-- include(controllers/ticket/delete.md) -->
<!-- include(controllers/user/delete.md) -->
