FORMAT: 1A
HOST: BASE_URL

# API Title
[Markdown](http://daringfireball.net/projects/markdown/syntax) **formatted** description.

<!-- include(header.md) -->

# Data Structures
<!-- include(models/user.md) -->
<!-- include(models/ticket.md) -->



# Group User
<!-- include(controllers/user.md) -->

# Group Ticket
<!-- include(controllers/ticket.md) -->




<!-- include(footer.md) -->
